version: 2.1

jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  deploy_to_render:
    docker:
      - image: render/render-cli:latest
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: japnesefood
          command: |
            render deploy --build-dir /tmp/workspace/dist

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy_to_render:
          requires:
            - build
