version: 2.1

executors:
  node-executor:
    docker:
      - image: node:latest 

jobs:
  deploy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: japnesefood
          command: |
            npm install -g vercel
            vercel login --token SaQl4hveWPavyOrlDFXDfAwa
            vercel --prod

workflows:
  version: 2
  deploy:
    jobs:
      - deploy
