version: 2.1

jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  deploy_to_ec2:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Install SSH key
          command: echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
      - run:
          name: Deploy to EC2
          command: |
            scp -i ~/.ssh/id_rsa -r dist ubuntu@ec2-65-2-148-71.ap-south-1.compute.amazonaws.com:/home/ubuntu/japnesefood
            ssh -i ~/.ssh/id_rsa ubuntu@ec2-65-2-148-71.ap-south-1.compute.amazonaws.com 'cd /home/ubuntu/japnesefood && pm2 restart japnesefood'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy_to_ec2:
          requires:
            - build
