version: 2.1

executors:
  node-executor:
    docker:
      - image: node:latest 

jobs:
  build_and_deploy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build 
      - persist_to_workspace:
          root: /app
          paths:
            - dist

  deploy:
    executor: node-executor
    steps:
      - attach_workspace:
          at: /app
      - run:
          name: japnesefood
          command: |
            npm install -g vercel
            vercel login --token SaQl4hveWPavyOrlDFXDfAwa
            vercel --prod dist

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy
      - deploy:
          requires:
            - build_and_deploy
