version: 2.1

jobs:
  build_and_deploy:
    docker:
      - image: node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  deploy_to_vercel:
    docker:
      - image: node:latest
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: japnesefood
          command: |
            npm install -g vercel
            vercel login # Use 'vercel login' without a token
            cd /tmp/workspace
            vercel --prod dist --yes

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy
      - deploy_to_vercel:
          requires:
            - build_and_deploy
